### PR TITLE
Format markdown for mutating state anti-pattern

### PR DESCRIPTION
**Pull request by markov00**

### CODE REVIEW

**Comment by Reda-bx** [comment]
@markov00 thank you, but could you please convert it to markdwon?

**Comment by Ch-Valentine** [comment]
@Reda-bx, i did that, but few minutes later. https://github.com/vasanthk/react-bits/pull/26/files

**Comment by markov00** [comment]
@Reda-bx I think @Ch-Valentine has a better shape, I will close this issue

**Comment by Reda-bx** [comment]
awesome guys

**Pull request closed without merging**
