### PR TITLE
Gitbook intergration

### PR DESCRIPTION
**Pull request by Reda-bx**
here is an example: https://reda-bx.gitbooks.io/react-bits/content, just create a gitbook account and link the repo there

### CODE REVIEW

**Comment by vasanthk** [comment]
This is great 🎉 👍 🥇 
Really like where this is going 😄

**Comment by Reda-bx** [comment]
Glad to help

**Comment by Reda-bx** [comment]
@vasanthk shall we merge  😄?

**Comment by vasanthk** [comment]
@Reda-bx Can you update the READ ME etc. Is it  possible to get it up with a custom url ?

**Comment by Reda-bx** [comment]
@vasanthk yeah I'll do that, can you create an account on gitbook.com and link this repo? ( I dont have access to do that).

**Comment by vasanthk** [comment]
@Reda-bx It's available here https://vasanthk.gitbooks.io/react-bits/content/
Any ways to customize the url?

**Comment by Reda-bx** [comment]
@vasanthk awesome, can you put it in the repo description, so people can find it easily?

**Comment by andys8** [comment]
Would be great to [allow PDF and book format exports](https://www.gitbook.com/book/vasanthk/react-bits/discussions/3). Thanks for the effort 😊

**Pull request merged**
