### PR TITLE
Using Pure Components instead of Using recompose

### PR DESCRIPTION
**Pull request by frooeyzanny**

### CODE REVIEW

**Comment by Nathan-Schwartz** [comment]
Nice catch 👍

**Comment by vasanthk** [comment]
@frooeyzanny Thank you :)

**Comment by sejoker** [comment]
@vasanthk you should redeploy after the merge. The link is broken at the moment.
screen shot 2017-04-08 at 10 21 26 pm

**Comment by vasanthk** [comment]
@frooeyzanny Thanks, the link needs to be updated in [Summary.md](https://github.com/vasanthk/react-bits/commit/ffa41045958e8aee8fc94443528314e5a6407e83) as well :)

Gitbook auto-deploys on every commit.

**Pull request merged**
